name: Compile all

on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        week: ["w00_init"]
    steps:
      - uses: actions/checkout@v2
      - name: compile week ${{ matrix.week }} with xelatex
        uses: ./.github/actions/xelatex-week
        with:
          folder: ${{ matrix.week }}
      - uses: actions/upload-artifact@v2
        with:
          name: Slides ${{ matrix.week }}
          path: ${{ matrix.week }}/*.pdf
