name: Compile all

on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile with xelatex
        uses: marcomicera/xelatex-action@v0.6
        with:
          input-file: "w00_init/t01_big_picture.tex"
