name: Compile all

on: push

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        week: [
            "w00_init",
            "w01_big_picture",
            "w02_basics",
            "w03_policy_evaluation",
            "w04_model_free_control",
            "w05_function_approx",
            "w06_deep_rl",
            "w07_policy_search",
            "w08_exploration",
            "w09_meta_rl"
          ]
    steps:
      - uses: actions/checkout@v2
      - name: compile week ${{ matrix.week }} with xelatex
        uses: ./.github/actions/xelatex-week
        with:
          folder: ${{ matrix.week }}
      - uses: actions/upload-artifact@v2
        with:
          name: Slides ${{ matrix.week }}
          path: ${{ matrix.week }}/*.pdf
  merge:
    name: Merge slides
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        week: [
            "w00_init",
            "w01_big_picture",
            "w02_basics",
            "w03_policy_evaluation",
            "w04_model_free_control",
            "w05_function_approx",
            "w06_deep_rl",
            "w07_policy_search",
            "w08_exploration",
            "w09_meta_rl"
        ]
        steps:
          - name: Install pdftk
            run: |
              - apt update && apt install pdftk
              - mkdir slides/
          - uses: actions/download-artifact@v2
            with:
              name: Slides ${{ matrix.week }}
          - name: Merge slides for week ${{ matrix.week }} with xelatex
            run: |
              - pdftk ${{ matrix.week }}/t*.pdf cat output slides/${{ matrix.week }}.pdf
          - uses: actions/upload-artifact@v2
            with:
              name: Merged slides
              path: slides/*.pdf

